# Este archivo le dice a Netlify cómo construir y desplegar tu sitio.

[build]
  # Esta es la carpeta que Netlify publicará. Contiene tu index.html, etc.
  publish = "/"
  
  # Esta le dice a Netlify dónde encontrar tus funciones serverless.
  functions = "functions/"

